
spring.application.name=LiterAlura
spring.datasource.url=jdbc:postgresql://localhost/literalura_db
spring.datasource.username=postgres
spring.datasource.password=bancodedados
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
